# Generated by Django 4.2.6 on 2023-11-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updates_At',
            new_name='updated_at',
        ),
    ]
